# Generated by Django 2.0.2 on 2018-05-04 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180504_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 7, 59, 52, 110003, tzinfo=utc)),
        ),
    ]
