# Generated by Django 2.0.2 on 2018-05-05 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180505_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 7, 16, 5, 887048, tzinfo=utc)),
        ),
    ]
